-- Clearo demo seed data
-- Run this whole file manually against the demo Neon branch after migrations.
--
-- Demo credentials:
--   Patient:      patient.demo@clearo.test / DemoPatient123! / OTP 000000
--   Clinic admin: clinic.admin@clearo.test / DemoClinic123!
--   Clinic staff: clinic.staff@clearo.test / DemoStaff123!
--
-- The clinic admin owns all seeded clinics.
-- Only Northside Imaging Melbourne has public bookable slots.

BEGIN;

DELETE FROM public.auth_accounts WHERE "userId" IN (SELECT id FROM public.auth_users WHERE lower(email) = 'patient.demo@clearo.test');
DELETE FROM public.auth_sessions WHERE "userId" IN (SELECT id FROM public.auth_users WHERE lower(email) = 'patient.demo@clearo.test');
DELETE FROM public.audit_logs WHERE user_id IN (SELECT id FROM public.auth_users WHERE lower(email) = 'patient.demo@clearo.test');
DELETE FROM public.patient_profiles WHERE user_id IN (SELECT id FROM public.auth_users WHERE lower(email) = 'patient.demo@clearo.test');
DELETE FROM public.auth_users WHERE lower(email) = 'patient.demo@clearo.test';
DELETE FROM clinic.users WHERE normalized_email IN ('clinic.admin@clearo.test', 'clinic.staff@clearo.test');
DELETE FROM public.clinics WHERE lower(email) IN ('northside.demo@clearo.test', 'yarra.demo@clearo.test', 'bayview.demo@clearo.test', 'harbour.demo@clearo.test', 'innerwest.demo@clearo.test', 'parramatta.demo@clearo.test');

INSERT INTO public.scan_types (name, description, icon, requires_referral, prep_instructions, safety_question_set) SELECT 'MRI', 'Magnetic resonance imaging for soft tissue and neurological scans.', 'magnet', true, 'Bring your referral and remove metal objects before the appointment.', '[{"id":"implants","question":"Do you have any implanted devices?","action":"require_approval"},{"id":"pregnancy","question":"Are you pregnant or possibly pregnant?","action":"require_approval"}]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.scan_types WHERE lower(name) = 'mri');
INSERT INTO public.scan_types (name, description, icon, requires_referral, prep_instructions, safety_question_set) SELECT 'CT Scan', 'Cross-sectional imaging for diagnostic assessment.', 'scan', true, 'Bring your referral. Fasting may be required for contrast studies.', '[{"id":"contrast","question":"Have you previously reacted to contrast?","action":"require_approval"}]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.scan_types WHERE lower(name) = 'ct scan');
INSERT INTO public.scan_types (name, description, icon, requires_referral, prep_instructions, safety_question_set) SELECT 'X-Ray', 'Common imaging for bones, chest, and joint assessment.', 'bone', true, 'Bring your referral and any previous imaging if available.', '[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.scan_types WHERE lower(name) = 'x-ray');
INSERT INTO public.scan_types (name, description, icon, requires_referral, prep_instructions, safety_question_set) SELECT 'Ultrasound', 'Sound wave imaging for soft tissue, abdominal, and pregnancy scans.', 'waves', true, 'Some scans require water intake or fasting. Check clinic instructions.', '[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.scan_types WHERE lower(name) = 'ultrasound');

UPDATE public.scan_types SET description = 'Magnetic resonance imaging for soft tissue and neurological scans.', icon = 'magnet', requires_referral = true, prep_instructions = 'Bring your referral and remove metal objects before the appointment.', safety_question_set = '[{"id":"implants","question":"Do you have any implanted devices?","action":"require_approval"},{"id":"pregnancy","question":"Are you pregnant or possibly pregnant?","action":"require_approval"}]'::jsonb WHERE lower(name) = 'mri';
UPDATE public.scan_types SET description = 'Cross-sectional imaging for diagnostic assessment.', icon = 'scan', requires_referral = true, prep_instructions = 'Bring your referral. Fasting may be required for contrast studies.', safety_question_set = '[{"id":"contrast","question":"Have you previously reacted to contrast?","action":"require_approval"}]'::jsonb WHERE lower(name) = 'ct scan';
UPDATE public.scan_types SET description = 'Common imaging for bones, chest, and joint assessment.', icon = 'bone', requires_referral = true, prep_instructions = 'Bring your referral and any previous imaging if available.', safety_question_set = '[]'::jsonb WHERE lower(name) = 'x-ray';
UPDATE public.scan_types SET description = 'Sound wave imaging for soft tissue, abdominal, and pregnancy scans.', icon = 'waves', requires_referral = true, prep_instructions = 'Some scans require water intake or fasting. Check clinic instructions.', safety_question_set = '[]'::jsonb WHERE lower(name) = 'ultrasound';

INSERT INTO public.auth_users (name, email, "emailVerified", role) VALUES ('Avery Demo', 'patient.demo@clearo.test', NOW(), 'patient');
INSERT INTO public.auth_accounts ("userId", provider, type, "providerAccountId", password) SELECT id, 'credentials', 'credentials', id::text, '$2a$12$V76p2kFKfGawezaaAV7aYuYS/YlnFVEAcr8uolU/fjZ1Tn31y8DHm' FROM public.auth_users WHERE lower(email) = 'patient.demo@clearo.test';

INSERT INTO clinic.users (email, normalized_email, name, password_hash, email_verified_at, status) VALUES ('clinic.admin@clearo.test', 'clinic.admin@clearo.test', 'Dr Morgan Admin', '$2a$12$7exH/u4gEkVZldoWwYGfTeRTNb8SNeaukNAlBYPWX40qHqr7OH8g.', NOW(), 'active');
INSERT INTO clinic.users (email, normalized_email, name, password_hash, email_verified_at, status) VALUES ('clinic.staff@clearo.test', 'clinic.staff@clearo.test', 'Taylor Staff', '$2a$12$f9DGGqFQano/JJ.a6rfnkORQXUxAEDiubuzuNi/Y5yCYN11MXMTa6', NOW(), 'active');

INSERT INTO public.clinics (name, description, address, city, state, zip_code, latitude, longitude, phone, email, image_url, rating, total_reviews, approval_status, approved_at, is_verified) VALUES ('Northside Imaging Melbourne', 'Synthetic demo imaging clinic with MRI, CT, X-Ray, and ultrasound appointments.', '120 Demo Street', 'Melbourne', 'VIC', '3000', -37.8136, 144.9631, '03 7000 1000', 'northside.demo@clearo.test', 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?auto=format&fit=crop&w=1200&q=80', 0, 0, 'approved', NOW(), true);
INSERT INTO public.clinics (name, description, address, city, state, zip_code, latitude, longitude, phone, email, image_url, rating, total_reviews, approval_status, approved_at, is_verified) VALUES ('Yarra Diagnostic Imaging', 'Synthetic demo clinic for comparing listed scan pricing and appointment options.', '44 River Demo Road', 'Richmond', 'VIC', '3121', -37.8200, 145.0000, '03 7000 2000', 'yarra.demo@clearo.test', 'https://images.unsplash.com/photo-1504439468489-c8920d796a29?auto=format&fit=crop&w=1200&q=80', 0, 0, 'approved', NOW(), true);
INSERT INTO public.clinics (name, description, address, city, state, zip_code, latitude, longitude, phone, email, image_url, rating, total_reviews, approval_status, approved_at, is_verified) VALUES ('Bayview Radiology Centre', 'Synthetic demo radiology centre with weekday appointment slots.', '9 Bay Demo Avenue', 'St Kilda', 'VIC', '3182', -37.8676, 144.9809, '03 7000 3000', 'bayview.demo@clearo.test', 'https://images.unsplash.com/photo-1587351021759-3e566b6af7cc?auto=format&fit=crop&w=1200&q=80', 0, 0, 'approved', NOW(), true);
INSERT INTO public.clinics (name, description, address, city, state, zip_code, latitude, longitude, phone, email, image_url, rating, total_reviews, approval_status, approved_at, is_verified) VALUES ('Harbour City Imaging Sydney', 'Synthetic demo Sydney clinic with listed MRI, CT, X-Ray, and ultrasound options.', '18 Harbour Demo Lane', 'Sydney', 'NSW', '2000', -33.8688, 151.2093, '02 8000 1000', 'harbour.demo@clearo.test', 'https://images.unsplash.com/photo-1505751172876-fa1923c5c528?auto=format&fit=crop&w=1200&q=80', 0, 0, 'approved', NOW(), true);
INSERT INTO public.clinics (name, description, address, city, state, zip_code, latitude, longitude, phone, email, image_url, rating, total_reviews, approval_status, approved_at, is_verified) VALUES ('Inner West Diagnostic Imaging', 'Synthetic demo clinic for Sydney appointment availability and pricing comparison.', '62 Demo Road', 'Newtown', 'NSW', '2042', -33.8981, 151.1745, '02 8000 2000', 'innerwest.demo@clearo.test', 'https://images.unsplash.com/photo-1516549655169-df83a0774514?auto=format&fit=crop&w=1200&q=80', 0, 0, 'approved', NOW(), true);
INSERT INTO public.clinics (name, description, address, city, state, zip_code, latitude, longitude, phone, email, image_url, rating, total_reviews, approval_status, approved_at, is_verified) VALUES ('Parramatta Radiology Centre', 'Synthetic demo radiology centre with weekday appointment slots in Western Sydney.', '7 Demo Square', 'Parramatta', 'NSW', '2150', -33.8148, 151.0017, '02 8000 3000', 'parramatta.demo@clearo.test', 'https://images.unsplash.com/photo-1538108149393-fbbd81895907?auto=format&fit=crop&w=1200&q=80', 0, 0, 'approved', NOW(), true);

INSERT INTO clinic.memberships (clinic_id, clinic_user_id, role, status, accepted_at) SELECT c.id, cu.id, 'owner', 'active', NOW() FROM public.clinics c CROSS JOIN clinic.users cu WHERE lower(c.email) IN ('northside.demo@clearo.test', 'yarra.demo@clearo.test', 'bayview.demo@clearo.test', 'harbour.demo@clearo.test', 'innerwest.demo@clearo.test', 'parramatta.demo@clearo.test') AND cu.normalized_email = 'clinic.admin@clearo.test';
INSERT INTO clinic.memberships (clinic_id, clinic_user_id, role, status, accepted_at) SELECT c.id, cu.id, 'staff', 'active', NOW() FROM public.clinics c CROSS JOIN clinic.users cu WHERE lower(c.email) = 'northside.demo@clearo.test' AND cu.normalized_email = 'clinic.staff@clearo.test';

INSERT INTO public.clinic_hours (clinic_id, day_of_week, open_time, close_time, is_closed) SELECT c.id, day_number, '08:30'::time, '17:00'::time, false FROM public.clinics c CROSS JOIN generate_series(1, 5) AS days(day_number) WHERE lower(c.email) IN ('northside.demo@clearo.test', 'yarra.demo@clearo.test', 'bayview.demo@clearo.test', 'harbour.demo@clearo.test', 'innerwest.demo@clearo.test', 'parramatta.demo@clearo.test');

INSERT INTO public.clinic_scans (clinic_id, scan_type_id, price, duration_minutes, available, requires_referral, prep_instructions) SELECT c.id, st.id, p.price, 30, true, true, 'Bring your referral and any previous imaging if available.' FROM public.clinics c JOIN (VALUES ('northside.demo@clearo.test','MRI',520),('northside.demo@clearo.test','CT Scan',360),('northside.demo@clearo.test','X-Ray',95),('northside.demo@clearo.test','Ultrasound',180),('yarra.demo@clearo.test','MRI',560),('yarra.demo@clearo.test','CT Scan',390),('yarra.demo@clearo.test','X-Ray',110),('yarra.demo@clearo.test','Ultrasound',205),('bayview.demo@clearo.test','MRI',610),('bayview.demo@clearo.test','CT Scan',420),('bayview.demo@clearo.test','X-Ray',125),('bayview.demo@clearo.test','Ultrasound',225),('harbour.demo@clearo.test','MRI',540),('harbour.demo@clearo.test','CT Scan',370),('harbour.demo@clearo.test','X-Ray',105),('harbour.demo@clearo.test','Ultrasound',190),('innerwest.demo@clearo.test','MRI',575),('innerwest.demo@clearo.test','CT Scan',405),('innerwest.demo@clearo.test','X-Ray',115),('innerwest.demo@clearo.test','Ultrasound',215),('parramatta.demo@clearo.test','MRI',595),('parramatta.demo@clearo.test','CT Scan',415),('parramatta.demo@clearo.test','X-Ray',120),('parramatta.demo@clearo.test','Ultrasound',220)) AS p(clinic_email, scan_name, price) ON lower(c.email) = p.clinic_email JOIN public.scan_types st ON lower(st.name) = lower(p.scan_name);

INSERT INTO public.machines (clinic_id, scan_type_id, machine_name, manufacturer, model, is_active) SELECT c.id, st.id, st.name || ' Room', 'DemoMed', 'DX-100', true FROM public.clinics c CROSS JOIN public.scan_types st WHERE lower(c.email) IN ('northside.demo@clearo.test', 'yarra.demo@clearo.test', 'bayview.demo@clearo.test', 'harbour.demo@clearo.test', 'innerwest.demo@clearo.test', 'parramatta.demo@clearo.test') AND lower(st.name) IN ('mri', 'ct scan', 'x-ray', 'ultrasound');

INSERT INTO public.available_slots (clinic_id, machine_id, slot_date, slot_time, duration_minutes, is_available) SELECT m.clinic_id, m.id, slot_day::date, slot_time::time, 30, true FROM public.machines m JOIN public.clinics c ON c.id = m.clinic_id CROSS JOIN generate_series(CURRENT_DATE + INTERVAL '1 day', CURRENT_DATE + INTERVAL '21 days', INTERVAL '1 day') AS days(slot_day) CROSS JOIN (VALUES ('09:00'), ('11:00'), ('14:00')) AS times(slot_time) WHERE lower(c.email) = 'northside.demo@clearo.test' AND EXTRACT(ISODOW FROM slot_day) BETWEEN 1 AND 5 ON CONFLICT DO NOTHING;

COMMIT;

SELECT 'public.clinics' AS table_name, COUNT(*)::int AS demo_rows FROM public.clinics WHERE lower(email) IN ('northside.demo@clearo.test', 'yarra.demo@clearo.test', 'bayview.demo@clearo.test', 'harbour.demo@clearo.test', 'innerwest.demo@clearo.test', 'parramatta.demo@clearo.test')
UNION ALL SELECT 'public.auth_users', COUNT(*)::int FROM public.auth_users WHERE lower(email) = 'patient.demo@clearo.test'
UNION ALL SELECT 'clinic.users', COUNT(*)::int FROM clinic.users WHERE normalized_email IN ('clinic.admin@clearo.test', 'clinic.staff@clearo.test')
UNION ALL SELECT 'clinic.memberships', COUNT(*)::int FROM clinic.memberships cm JOIN clinic.users cu ON cu.id = cm.clinic_user_id WHERE cu.normalized_email IN ('clinic.admin@clearo.test', 'clinic.staff@clearo.test')
UNION ALL SELECT 'public.clinic_scans', COUNT(*)::int FROM public.clinic_scans cs JOIN public.clinics c ON c.id = cs.clinic_id WHERE lower(c.email) IN ('northside.demo@clearo.test', 'yarra.demo@clearo.test', 'bayview.demo@clearo.test', 'harbour.demo@clearo.test', 'innerwest.demo@clearo.test', 'parramatta.demo@clearo.test')
UNION ALL SELECT 'public.machines', COUNT(*)::int FROM public.machines m JOIN public.clinics c ON c.id = m.clinic_id WHERE lower(c.email) IN ('northside.demo@clearo.test', 'yarra.demo@clearo.test', 'bayview.demo@clearo.test', 'harbour.demo@clearo.test', 'innerwest.demo@clearo.test', 'parramatta.demo@clearo.test')
UNION ALL SELECT 'public.available_slots', COUNT(*)::int FROM public.available_slots s JOIN public.clinics c ON c.id = s.clinic_id WHERE lower(c.email) = 'northside.demo@clearo.test';
