/* eslint-disable */
// This file is generated by scripts/generate-api-routes.mjs.
// Do not edit manually.
import * as routeModule0 from "../app/api/auth/login-otp/send/route.js";
import * as routeModule1 from "../app/api/auth/login-otp/verify/route.js";
import * as routeModule2 from "../app/api/clinic-admin/slots/calendar/route.js";
import * as routeModule3 from "../app/api/clinic-admin/slots/range-availability/route.js";
import * as routeModule4 from "../app/api/clinic-admin/slots/summary/route.js";
import * as routeModule5 from "../app/api/clinic/auth/forgot-password/route.js";
import * as routeModule6 from "../app/api/clinic/auth/me/route.js";
import * as routeModule7 from "../app/api/clinic/auth/reset-password/route.js";
import * as routeModule8 from "../app/api/clinic/auth/sessions/route.js";
import * as routeModule9 from "../app/api/clinic/auth/signin/route.js";
import * as routeModule10 from "../app/api/clinic/auth/signout/route.js";
import * as routeModule11 from "../app/api/clinic/auth/signup/route.js";
import * as routeModule12 from "../app/api/clinic/auth/verify-email/route.js";
import * as routeModule13 from "../app/api/clinic/mfa/challenge/route.js";
import * as routeModule14 from "../app/api/clinic/mfa/setup/route.js";
import * as routeModule15 from "../app/api/clinic/mfa/status/route.js";
import * as routeModule16 from "../app/api/clinic/mfa/verify/route.js";
import * as routeModule17 from "../app/api/bookings/[id]/cancel/route.js";
import * as routeModule18 from "../app/api/bookings/[id]/reschedule/route.js";
import * as routeModule19 from "../app/api/bookings/[id]/verify-token/route.js";
import * as routeModule20 from "../app/api/referrals/files/[fileId]/route.js";
import * as routeModule21 from "../app/api/auth/expo-web-success/route.js";
import * as routeModule22 from "../app/api/auth/forgot-password/route.js";
import * as routeModule23 from "../app/api/auth/resend-verification/route.js";
import * as routeModule24 from "../app/api/auth/reset-password/route.js";
import * as routeModule25 from "../app/api/auth/signup/route.js";
import * as routeModule26 from "../app/api/auth/token/route.js";
import * as routeModule27 from "../app/api/auth/verify-email/route.js";
import * as routeModule28 from "../app/api/captcha/config/route.js";
import * as routeModule29 from "../app/api/captcha/events/route.js";
import * as routeModule30 from "../app/api/clinic-admin/bookings/route.js";
import * as routeModule31 from "../app/api/clinic-admin/clinic/route.js";
import * as routeModule32 from "../app/api/clinic-admin/clinic-hours/route.js";
import * as routeModule33 from "../app/api/clinic-admin/clinic-scans/route.js";
import * as routeModule34 from "../app/api/clinic-admin/clinics/route.js";
import * as routeModule35 from "../app/api/clinic-admin/machines/route.js";
import * as routeModule36 from "../app/api/clinic/audit-logs/route.js";
import * as routeModule37 from "../app/api/clinic/invitations/route.js";
import * as routeModule38 from "../app/api/clinics/availability/route.js";
import * as routeModule39 from "../app/api/jobs/referral-reminders/route.js";
import * as routeModule40 from "../app/api/locations/cities/route.js";
import * as routeModule41 from "../app/api/maps/config/route.js";
import * as routeModule42 from "../app/api/seo/resolve/route.js";
import * as routeModule43 from "../app/api/slots/available/route.js";
import * as routeModule44 from "../app/api/slots/generate/route.js";
import * as routeModule45 from "../app/api/slots/suggestions/route.js";
import * as routeModule46 from "../app/api/user/delete-account/route.js";
import * as routeModule47 from "../app/api/user/patient-profile/route.js";
import * as routeModule48 from "../app/api/user/profile/route.js";
import * as routeModule49 from "../app/api/bookings/[id]/route.js";
import * as routeModule50 from "../app/api/clinics/[id]/route.js";
import * as routeModule51 from "../app/api/auth/[...auth]/route.js";
import * as routeModule52 from "../app/api/bookings/route.js";
import * as routeModule53 from "../app/api/clinic-onboarding/route.js";
import * as routeModule54 from "../app/api/clinics/route.js";
import * as routeModule55 from "../app/api/csrf-token/route.js";
import * as routeModule56 from "../app/api/csrf-token-simple/route.js";
import * as routeModule57 from "../app/api/locations/route.js";
import * as routeModule58 from "../app/api/newsletter/route.js";
import * as routeModule59 from "../app/api/ping/route.js";
import * as routeModule60 from "../app/api/ready/route.js";
import * as routeModule61 from "../app/api/scan-types/route.js";
import * as routeModule62 from "../app/api/track-visit/route.js";
import * as routeModule63 from "../app/api/upload/route.js";

type Method = "GET" | "POST" | "PUT" | "PATCH" | "DELETE" | "HEAD" | "OPTIONS";
type RouteParams = Record<string, string>;
type RouteContext = { params: RouteParams };
type RouteHandler = (request: Request, context?: RouteContext) => Response | Promise<Response>;
type RouteModule = Partial<Record<Method, RouteHandler>>;

export type ApiRouteDefinition = {
  path: string;
  source: string;
  module: RouteModule;
};

export const apiRouteDefinitions: ApiRouteDefinition[] = [
  { path: "/auth/login-otp/send", source: "auth/login-otp/send", module: routeModule0 as RouteModule },
  { path: "/auth/login-otp/verify", source: "auth/login-otp/verify", module: routeModule1 as RouteModule },
  { path: "/clinic-admin/slots/calendar", source: "clinic-admin/slots/calendar", module: routeModule2 as RouteModule },
  { path: "/clinic-admin/slots/range-availability", source: "clinic-admin/slots/range-availability", module: routeModule3 as RouteModule },
  { path: "/clinic-admin/slots/summary", source: "clinic-admin/slots/summary", module: routeModule4 as RouteModule },
  { path: "/clinic/auth/forgot-password", source: "clinic/auth/forgot-password", module: routeModule5 as RouteModule },
  { path: "/clinic/auth/me", source: "clinic/auth/me", module: routeModule6 as RouteModule },
  { path: "/clinic/auth/reset-password", source: "clinic/auth/reset-password", module: routeModule7 as RouteModule },
  { path: "/clinic/auth/sessions", source: "clinic/auth/sessions", module: routeModule8 as RouteModule },
  { path: "/clinic/auth/signin", source: "clinic/auth/signin", module: routeModule9 as RouteModule },
  { path: "/clinic/auth/signout", source: "clinic/auth/signout", module: routeModule10 as RouteModule },
  { path: "/clinic/auth/signup", source: "clinic/auth/signup", module: routeModule11 as RouteModule },
  { path: "/clinic/auth/verify-email", source: "clinic/auth/verify-email", module: routeModule12 as RouteModule },
  { path: "/clinic/mfa/challenge", source: "clinic/mfa/challenge", module: routeModule13 as RouteModule },
  { path: "/clinic/mfa/setup", source: "clinic/mfa/setup", module: routeModule14 as RouteModule },
  { path: "/clinic/mfa/status", source: "clinic/mfa/status", module: routeModule15 as RouteModule },
  { path: "/clinic/mfa/verify", source: "clinic/mfa/verify", module: routeModule16 as RouteModule },
  { path: "/bookings/:id/cancel", source: "bookings/[id]/cancel", module: routeModule17 as RouteModule },
  { path: "/bookings/:id/reschedule", source: "bookings/[id]/reschedule", module: routeModule18 as RouteModule },
  { path: "/bookings/:id/verify-token", source: "bookings/[id]/verify-token", module: routeModule19 as RouteModule },
  { path: "/referrals/files/:fileId", source: "referrals/files/[fileId]", module: routeModule20 as RouteModule },
  { path: "/auth/expo-web-success", source: "auth/expo-web-success", module: routeModule21 as RouteModule },
  { path: "/auth/forgot-password", source: "auth/forgot-password", module: routeModule22 as RouteModule },
  { path: "/auth/resend-verification", source: "auth/resend-verification", module: routeModule23 as RouteModule },
  { path: "/auth/reset-password", source: "auth/reset-password", module: routeModule24 as RouteModule },
  { path: "/auth/signup", source: "auth/signup", module: routeModule25 as RouteModule },
  { path: "/auth/token", source: "auth/token", module: routeModule26 as RouteModule },
  { path: "/auth/verify-email", source: "auth/verify-email", module: routeModule27 as RouteModule },
  { path: "/captcha/config", source: "captcha/config", module: routeModule28 as RouteModule },
  { path: "/captcha/events", source: "captcha/events", module: routeModule29 as RouteModule },
  { path: "/clinic-admin/bookings", source: "clinic-admin/bookings", module: routeModule30 as RouteModule },
  { path: "/clinic-admin/clinic", source: "clinic-admin/clinic", module: routeModule31 as RouteModule },
  { path: "/clinic-admin/clinic-hours", source: "clinic-admin/clinic-hours", module: routeModule32 as RouteModule },
  { path: "/clinic-admin/clinic-scans", source: "clinic-admin/clinic-scans", module: routeModule33 as RouteModule },
  { path: "/clinic-admin/clinics", source: "clinic-admin/clinics", module: routeModule34 as RouteModule },
  { path: "/clinic-admin/machines", source: "clinic-admin/machines", module: routeModule35 as RouteModule },
  { path: "/clinic/audit-logs", source: "clinic/audit-logs", module: routeModule36 as RouteModule },
  { path: "/clinic/invitations", source: "clinic/invitations", module: routeModule37 as RouteModule },
  { path: "/clinics/availability", source: "clinics/availability", module: routeModule38 as RouteModule },
  { path: "/jobs/referral-reminders", source: "jobs/referral-reminders", module: routeModule39 as RouteModule },
  { path: "/locations/cities", source: "locations/cities", module: routeModule40 as RouteModule },
  { path: "/maps/config", source: "maps/config", module: routeModule41 as RouteModule },
  { path: "/seo/resolve", source: "seo/resolve", module: routeModule42 as RouteModule },
  { path: "/slots/available", source: "slots/available", module: routeModule43 as RouteModule },
  { path: "/slots/generate", source: "slots/generate", module: routeModule44 as RouteModule },
  { path: "/slots/suggestions", source: "slots/suggestions", module: routeModule45 as RouteModule },
  { path: "/user/delete-account", source: "user/delete-account", module: routeModule46 as RouteModule },
  { path: "/user/patient-profile", source: "user/patient-profile", module: routeModule47 as RouteModule },
  { path: "/user/profile", source: "user/profile", module: routeModule48 as RouteModule },
  { path: "/bookings/:id", source: "bookings/[id]", module: routeModule49 as RouteModule },
  { path: "/clinics/:id", source: "clinics/[id]", module: routeModule50 as RouteModule },
  { path: "/auth/:auth{.+}", source: "auth/[...auth]", module: routeModule51 as RouteModule },
  { path: "/bookings", source: "bookings", module: routeModule52 as RouteModule },
  { path: "/clinic-onboarding", source: "clinic-onboarding", module: routeModule53 as RouteModule },
  { path: "/clinics", source: "clinics", module: routeModule54 as RouteModule },
  { path: "/csrf-token", source: "csrf-token", module: routeModule55 as RouteModule },
  { path: "/csrf-token-simple", source: "csrf-token-simple", module: routeModule56 as RouteModule },
  { path: "/locations", source: "locations", module: routeModule57 as RouteModule },
  { path: "/newsletter", source: "newsletter", module: routeModule58 as RouteModule },
  { path: "/ping", source: "ping", module: routeModule59 as RouteModule },
  { path: "/ready", source: "ready", module: routeModule60 as RouteModule },
  { path: "/scan-types", source: "scan-types", module: routeModule61 as RouteModule },
  { path: "/track-visit", source: "track-visit", module: routeModule62 as RouteModule },
  { path: "/upload", source: "upload", module: routeModule63 as RouteModule },
];
